[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nextdep_dsp_schema"
version = "0.0.7"
readme = "README.md"
dependencies = [
    "GitPython",
    "mmcif",
    "numpy",
    "paramiko",
    "psutil",
    "PyNaCl",
    "python-dateutil",
    "pytz",
    "rcsb.utils.io",
    "requests",
    "ruamel.yaml",
    "urllib3",
]

[project.optional-dependencies]
test = [
    "jsondiff",
    "jsonschema",
    "rcsb.db",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "build>=1.6.1",
]
